// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package db

import (
	"context"
	"database/sql"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (name, system_prompt, tools, model, parent_agent, permissions, config_path, loaded_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING name, system_prompt, tools, model, parent_agent, permissions, config_path, loaded_at
`

type CreateAgentParams struct {
	Name         string         `json:"name"`
	SystemPrompt string         `json:"system_prompt"`
	Tools        string         `json:"tools"`
	Model        sql.NullString `json:"model"`
	ParentAgent  sql.NullString `json:"parent_agent"`
	Permissions  string         `json:"permissions"`
	ConfigPath   sql.NullString `json:"config_path"`
	LoadedAt     int64          `json:"loaded_at"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.queryRow(ctx, q.createAgentStmt, createAgent,
		arg.Name,
		arg.SystemPrompt,
		arg.Tools,
		arg.Model,
		arg.ParentAgent,
		arg.Permissions,
		arg.ConfigPath,
		arg.LoadedAt,
	)
	var i Agent
	err := row.Scan(
		&i.Name,
		&i.SystemPrompt,
		&i.Tools,
		&i.Model,
		&i.ParentAgent,
		&i.Permissions,
		&i.ConfigPath,
		&i.LoadedAt,
	)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents WHERE name = ?
`

func (q *Queries) DeleteAgent(ctx context.Context, name string) error {
	_, err := q.exec(ctx, q.deleteAgentStmt, deleteAgent, name)
	return err
}

const getAgent = `-- name: GetAgent :one
SELECT name, system_prompt, tools, model, parent_agent, permissions, config_path, loaded_at FROM agents WHERE name = ?
`

func (q *Queries) GetAgent(ctx context.Context, name string) (Agent, error) {
	row := q.queryRow(ctx, q.getAgentStmt, getAgent, name)
	var i Agent
	err := row.Scan(
		&i.Name,
		&i.SystemPrompt,
		&i.Tools,
		&i.Model,
		&i.ParentAgent,
		&i.Permissions,
		&i.ConfigPath,
		&i.LoadedAt,
	)
	return i, err
}

const listAgents = `-- name: ListAgents :many
SELECT name, system_prompt, tools, model, parent_agent, permissions, config_path, loaded_at FROM agents ORDER BY name
`

func (q *Queries) ListAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.query(ctx, q.listAgentsStmt, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.Name,
			&i.SystemPrompt,
			&i.Tools,
			&i.Model,
			&i.ParentAgent,
			&i.Permissions,
			&i.ConfigPath,
			&i.LoadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
