// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createAgentStmt, err = db.PrepareContext(ctx, createAgent); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAgent: %w", err)
	}
	if q.createDelegationLogStmt, err = db.PrepareContext(ctx, createDelegationLog); err != nil {
		return nil, fmt.Errorf("error preparing query CreateDelegationLog: %w", err)
	}
	if q.createMemoryStmt, err = db.PrepareContext(ctx, createMemory); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMemory: %w", err)
	}
	if q.createMessageStmt, err = db.PrepareContext(ctx, createMessage); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMessage: %w", err)
	}
	if q.createSessionStmt, err = db.PrepareContext(ctx, createSession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSession: %w", err)
	}
	if q.deleteAgentStmt, err = db.PrepareContext(ctx, deleteAgent); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAgent: %w", err)
	}
	if q.deleteMemoryStmt, err = db.PrepareContext(ctx, deleteMemory); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMemory: %w", err)
	}
	if q.deleteMessageStmt, err = db.PrepareContext(ctx, deleteMessage); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMessage: %w", err)
	}
	if q.deleteSessionStmt, err = db.PrepareContext(ctx, deleteSession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSession: %w", err)
	}
	if q.deleteSessionMessagesStmt, err = db.PrepareContext(ctx, deleteSessionMessages); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionMessages: %w", err)
	}
	if q.getAgentStmt, err = db.PrepareContext(ctx, getAgent); err != nil {
		return nil, fmt.Errorf("error preparing query GetAgent: %w", err)
	}
	if q.getAllLeavesStmt, err = db.PrepareContext(ctx, getAllLeaves); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllLeaves: %w", err)
	}
	if q.getBranchFromRootToStmt, err = db.PrepareContext(ctx, getBranchFromRootTo); err != nil {
		return nil, fmt.Errorf("error preparing query GetBranchFromRootTo: %w", err)
	}
	if q.getMemoryStmt, err = db.PrepareContext(ctx, getMemory); err != nil {
		return nil, fmt.Errorf("error preparing query GetMemory: %w", err)
	}
	if q.getMessageStmt, err = db.PrepareContext(ctx, getMessage); err != nil {
		return nil, fmt.Errorf("error preparing query GetMessage: %w", err)
	}
	if q.getSessionByIDStmt, err = db.PrepareContext(ctx, getSessionByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionByID: %w", err)
	}
	if q.listAgentsStmt, err = db.PrepareContext(ctx, listAgents); err != nil {
		return nil, fmt.Errorf("error preparing query ListAgents: %w", err)
	}
	if q.listDelegationLogsBySessionStmt, err = db.PrepareContext(ctx, listDelegationLogsBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListDelegationLogsBySession: %w", err)
	}
	if q.listMemoryByAgentStmt, err = db.PrepareContext(ctx, listMemoryByAgent); err != nil {
		return nil, fmt.Errorf("error preparing query ListMemoryByAgent: %w", err)
	}
	if q.listMessagesBySessionStmt, err = db.PrepareContext(ctx, listMessagesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListMessagesBySession: %w", err)
	}
	if q.listSessionsStmt, err = db.PrepareContext(ctx, listSessions); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessions: %w", err)
	}
	if q.updateMessageStmt, err = db.PrepareContext(ctx, updateMessage); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMessage: %w", err)
	}
	if q.updateSessionStmt, err = db.PrepareContext(ctx, updateSession); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSession: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createAgentStmt != nil {
		if cerr := q.createAgentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAgentStmt: %w", cerr)
		}
	}
	if q.createDelegationLogStmt != nil {
		if cerr := q.createDelegationLogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createDelegationLogStmt: %w", cerr)
		}
	}
	if q.createMemoryStmt != nil {
		if cerr := q.createMemoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMemoryStmt: %w", cerr)
		}
	}
	if q.createMessageStmt != nil {
		if cerr := q.createMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMessageStmt: %w", cerr)
		}
	}
	if q.createSessionStmt != nil {
		if cerr := q.createSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSessionStmt: %w", cerr)
		}
	}
	if q.deleteAgentStmt != nil {
		if cerr := q.deleteAgentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAgentStmt: %w", cerr)
		}
	}
	if q.deleteMemoryStmt != nil {
		if cerr := q.deleteMemoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMemoryStmt: %w", cerr)
		}
	}
	if q.deleteMessageStmt != nil {
		if cerr := q.deleteMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMessageStmt: %w", cerr)
		}
	}
	if q.deleteSessionStmt != nil {
		if cerr := q.deleteSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionStmt: %w", cerr)
		}
	}
	if q.deleteSessionMessagesStmt != nil {
		if cerr := q.deleteSessionMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionMessagesStmt: %w", cerr)
		}
	}
	if q.getAgentStmt != nil {
		if cerr := q.getAgentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAgentStmt: %w", cerr)
		}
	}
	if q.getAllLeavesStmt != nil {
		if cerr := q.getAllLeavesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllLeavesStmt: %w", cerr)
		}
	}
	if q.getBranchFromRootToStmt != nil {
		if cerr := q.getBranchFromRootToStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBranchFromRootToStmt: %w", cerr)
		}
	}
	if q.getMemoryStmt != nil {
		if cerr := q.getMemoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMemoryStmt: %w", cerr)
		}
	}
	if q.getMessageStmt != nil {
		if cerr := q.getMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMessageStmt: %w", cerr)
		}
	}
	if q.getSessionByIDStmt != nil {
		if cerr := q.getSessionByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionByIDStmt: %w", cerr)
		}
	}
	if q.listAgentsStmt != nil {
		if cerr := q.listAgentsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAgentsStmt: %w", cerr)
		}
	}
	if q.listDelegationLogsBySessionStmt != nil {
		if cerr := q.listDelegationLogsBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDelegationLogsBySessionStmt: %w", cerr)
		}
	}
	if q.listMemoryByAgentStmt != nil {
		if cerr := q.listMemoryByAgentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMemoryByAgentStmt: %w", cerr)
		}
	}
	if q.listMessagesBySessionStmt != nil {
		if cerr := q.listMessagesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMessagesBySessionStmt: %w", cerr)
		}
	}
	if q.listSessionsStmt != nil {
		if cerr := q.listSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionsStmt: %w", cerr)
		}
	}
	if q.updateMessageStmt != nil {
		if cerr := q.updateMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMessageStmt: %w", cerr)
		}
	}
	if q.updateSessionStmt != nil {
		if cerr := q.updateSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                              DBTX
	tx                              *sql.Tx
	createAgentStmt                 *sql.Stmt
	createDelegationLogStmt         *sql.Stmt
	createMemoryStmt                *sql.Stmt
	createMessageStmt               *sql.Stmt
	createSessionStmt               *sql.Stmt
	deleteAgentStmt                 *sql.Stmt
	deleteMemoryStmt                *sql.Stmt
	deleteMessageStmt               *sql.Stmt
	deleteSessionStmt               *sql.Stmt
	deleteSessionMessagesStmt       *sql.Stmt
	getAgentStmt                    *sql.Stmt
	getAllLeavesStmt                *sql.Stmt
	getBranchFromRootToStmt         *sql.Stmt
	getMemoryStmt                   *sql.Stmt
	getMessageStmt                  *sql.Stmt
	getSessionByIDStmt              *sql.Stmt
	listAgentsStmt                  *sql.Stmt
	listDelegationLogsBySessionStmt *sql.Stmt
	listMemoryByAgentStmt           *sql.Stmt
	listMessagesBySessionStmt       *sql.Stmt
	listSessionsStmt                *sql.Stmt
	updateMessageStmt               *sql.Stmt
	updateSessionStmt               *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                              tx,
		tx:                              tx,
		createAgentStmt:                 q.createAgentStmt,
		createDelegationLogStmt:         q.createDelegationLogStmt,
		createMemoryStmt:                q.createMemoryStmt,
		createMessageStmt:               q.createMessageStmt,
		createSessionStmt:               q.createSessionStmt,
		deleteAgentStmt:                 q.deleteAgentStmt,
		deleteMemoryStmt:                q.deleteMemoryStmt,
		deleteMessageStmt:               q.deleteMessageStmt,
		deleteSessionStmt:               q.deleteSessionStmt,
		deleteSessionMessagesStmt:       q.deleteSessionMessagesStmt,
		getAgentStmt:                    q.getAgentStmt,
		getAllLeavesStmt:                q.getAllLeavesStmt,
		getBranchFromRootToStmt:         q.getBranchFromRootToStmt,
		getMemoryStmt:                   q.getMemoryStmt,
		getMessageStmt:                  q.getMessageStmt,
		getSessionByIDStmt:              q.getSessionByIDStmt,
		listAgentsStmt:                  q.listAgentsStmt,
		listDelegationLogsBySessionStmt: q.listDelegationLogsBySessionStmt,
		listMemoryByAgentStmt:           q.listMemoryByAgentStmt,
		listMessagesBySessionStmt:       q.listMessagesBySessionStmt,
		listSessionsStmt:                q.listSessionsStmt,
		updateMessageStmt:               q.updateMessageStmt,
		updateSessionStmt:               q.updateSessionStmt,
	}
}
