// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delegation_logs.sql

package db

import (
	"context"
	"database/sql"
)

const createDelegationLog = `-- name: CreateDelegationLog :one
INSERT INTO delegation_logs (id, parent_message_id, child_agent_name, child_session_id, task_description, result_summary, duration_ms, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, parent_message_id, child_agent_name, child_session_id, task_description, result_summary, duration_ms, created_at
`

type CreateDelegationLogParams struct {
	ID              string         `json:"id"`
	ParentMessageID string         `json:"parent_message_id"`
	ChildAgentName  string         `json:"child_agent_name"`
	ChildSessionID  sql.NullString `json:"child_session_id"`
	TaskDescription string         `json:"task_description"`
	ResultSummary   sql.NullString `json:"result_summary"`
	DurationMs      sql.NullInt64  `json:"duration_ms"`
	CreatedAt       int64          `json:"created_at"`
}

func (q *Queries) CreateDelegationLog(ctx context.Context, arg CreateDelegationLogParams) (DelegationLog, error) {
	row := q.queryRow(ctx, q.createDelegationLogStmt, createDelegationLog,
		arg.ID,
		arg.ParentMessageID,
		arg.ChildAgentName,
		arg.ChildSessionID,
		arg.TaskDescription,
		arg.ResultSummary,
		arg.DurationMs,
		arg.CreatedAt,
	)
	var i DelegationLog
	err := row.Scan(
		&i.ID,
		&i.ParentMessageID,
		&i.ChildAgentName,
		&i.ChildSessionID,
		&i.TaskDescription,
		&i.ResultSummary,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const listDelegationLogsBySession = `-- name: ListDelegationLogsBySession :many
SELECT dl.id, dl.parent_message_id, dl.child_agent_name, dl.child_session_id, dl.task_description, dl.result_summary, dl.duration_ms, dl.created_at FROM delegation_logs dl
INNER JOIN messages m ON dl.parent_message_id = m.id
WHERE m.session_id = ?
ORDER BY dl.created_at DESC
`

func (q *Queries) ListDelegationLogsBySession(ctx context.Context, sessionID string) ([]DelegationLog, error) {
	rows, err := q.query(ctx, q.listDelegationLogsBySessionStmt, listDelegationLogsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DelegationLog
	for rows.Next() {
		var i DelegationLog
		if err := rows.Scan(
			&i.ID,
			&i.ParentMessageID,
			&i.ChildAgentName,
			&i.ChildSessionID,
			&i.TaskDescription,
			&i.ResultSummary,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
