// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memory.sql

package db

import (
	"context"
	"database/sql"
)

const createMemory = `-- name: CreateMemory :one
INSERT INTO memory (id, agent_name, key, value, category, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, agent_name, "key", value, category, created_at, updated_at
`

type CreateMemoryParams struct {
	ID        string         `json:"id"`
	AgentName string         `json:"agent_name"`
	Key       string         `json:"key"`
	Value     string         `json:"value"`
	Category  sql.NullString `json:"category"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
}

func (q *Queries) CreateMemory(ctx context.Context, arg CreateMemoryParams) (Memory, error) {
	row := q.queryRow(ctx, q.createMemoryStmt, createMemory,
		arg.ID,
		arg.AgentName,
		arg.Key,
		arg.Value,
		arg.Category,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.AgentName,
		&i.Key,
		&i.Value,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMemory = `-- name: DeleteMemory :exec
DELETE FROM memory WHERE id = ?
`

func (q *Queries) DeleteMemory(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteMemoryStmt, deleteMemory, id)
	return err
}

const getMemory = `-- name: GetMemory :one
SELECT id, agent_name, "key", value, category, created_at, updated_at FROM memory WHERE agent_name = ? AND key = ?
`

type GetMemoryParams struct {
	AgentName string `json:"agent_name"`
	Key       string `json:"key"`
}

func (q *Queries) GetMemory(ctx context.Context, arg GetMemoryParams) (Memory, error) {
	row := q.queryRow(ctx, q.getMemoryStmt, getMemory, arg.AgentName, arg.Key)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.AgentName,
		&i.Key,
		&i.Value,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMemoryByAgent = `-- name: ListMemoryByAgent :many
SELECT id, agent_name, "key", value, category, created_at, updated_at FROM memory WHERE agent_name = ? ORDER BY updated_at DESC
`

func (q *Queries) ListMemoryByAgent(ctx context.Context, agentName string) ([]Memory, error) {
	rows, err := q.query(ctx, q.listMemoryByAgentStmt, listMemoryByAgent, agentName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Memory
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.AgentName,
			&i.Key,
			&i.Value,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
