// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"
	"database/sql"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (id, session_id, parent_id, role, parts, content, agent_name, tool_name, tool_call_id, tool_args, model, token_count, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, session_id, parent_id, role, parts, content, agent_name, tool_name, tool_call_id, tool_args, model, token_count, created_at, updated_at, finished_at
`

type CreateMessageParams struct {
	ID         string         `json:"id"`
	SessionID  string         `json:"session_id"`
	ParentID   sql.NullString `json:"parent_id"`
	Role       string         `json:"role"`
	Parts      string         `json:"parts"`
	Content    sql.NullString `json:"content"`
	AgentName  sql.NullString `json:"agent_name"`
	ToolName   sql.NullString `json:"tool_name"`
	ToolCallID sql.NullString `json:"tool_call_id"`
	ToolArgs   sql.NullString `json:"tool_args"`
	Model      sql.NullString `json:"model"`
	TokenCount sql.NullInt64  `json:"token_count"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.queryRow(ctx, q.createMessageStmt, createMessage,
		arg.ID,
		arg.SessionID,
		arg.ParentID,
		arg.Role,
		arg.Parts,
		arg.Content,
		arg.AgentName,
		arg.ToolName,
		arg.ToolCallID,
		arg.ToolArgs,
		arg.Model,
		arg.TokenCount,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ParentID,
		&i.Role,
		&i.Parts,
		&i.Content,
		&i.AgentName,
		&i.ToolName,
		&i.ToolCallID,
		&i.ToolArgs,
		&i.Model,
		&i.TokenCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages WHERE id = ?
`

func (q *Queries) DeleteMessage(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteMessageStmt, deleteMessage, id)
	return err
}

const deleteSessionMessages = `-- name: DeleteSessionMessages :exec
DELETE FROM messages WHERE session_id = ?
`

func (q *Queries) DeleteSessionMessages(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.deleteSessionMessagesStmt, deleteSessionMessages, sessionID)
	return err
}

const getAllLeaves = `-- name: GetAllLeaves :many
SELECT m.id, m.session_id, m.parent_id, m.role, m.parts, m.content, m.agent_name, m.tool_name, m.tool_call_id, m.tool_args, m.model, m.token_count, m.created_at, m.updated_at, m.finished_at FROM messages m
WHERE m.session_id = ?
AND m.id NOT IN (SELECT sub.parent_id FROM messages sub WHERE sub.parent_id IS NOT NULL AND sub.session_id = ?)
`

type GetAllLeavesParams struct {
	SessionID   string `json:"session_id"`
	SessionID_2 string `json:"session_id_2"`
}

func (q *Queries) GetAllLeaves(ctx context.Context, arg GetAllLeavesParams) ([]Message, error) {
	rows, err := q.query(ctx, q.getAllLeavesStmt, getAllLeaves, arg.SessionID, arg.SessionID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ParentID,
			&i.Role,
			&i.Parts,
			&i.Content,
			&i.AgentName,
			&i.ToolName,
			&i.ToolCallID,
			&i.ToolArgs,
			&i.Model,
			&i.TokenCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBranchFromRootTo = `-- name: GetBranchFromRootTo :many
WITH RECURSIVE branch AS (
    SELECT id, session_id, parent_id, role, parts, content, agent_name, tool_name, tool_call_id, tool_args, model, token_count, created_at, updated_at, finished_at FROM messages WHERE messages.id = ?
    UNION ALL
    SELECT m.id, m.session_id, m.parent_id, m.role, m.parts, m.content, m.agent_name, m.tool_name, m.tool_call_id, m.tool_args, m.model, m.token_count, m.created_at, m.updated_at, m.finished_at FROM messages m
    INNER JOIN branch b ON m.id = b.parent_id
)
SELECT id, session_id, parent_id, role, parts, content, agent_name, tool_name, tool_call_id, tool_args, model, token_count, created_at, updated_at, finished_at FROM branch ORDER BY created_at ASC
`

type GetBranchFromRootToRow struct {
	ID         string         `json:"id"`
	SessionID  string         `json:"session_id"`
	ParentID   sql.NullString `json:"parent_id"`
	Role       string         `json:"role"`
	Parts      string         `json:"parts"`
	Content    sql.NullString `json:"content"`
	AgentName  sql.NullString `json:"agent_name"`
	ToolName   sql.NullString `json:"tool_name"`
	ToolCallID sql.NullString `json:"tool_call_id"`
	ToolArgs   sql.NullString `json:"tool_args"`
	Model      sql.NullString `json:"model"`
	TokenCount sql.NullInt64  `json:"token_count"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
	FinishedAt sql.NullInt64  `json:"finished_at"`
}

func (q *Queries) GetBranchFromRootTo(ctx context.Context, id string) ([]GetBranchFromRootToRow, error) {
	rows, err := q.query(ctx, q.getBranchFromRootToStmt, getBranchFromRootTo, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBranchFromRootToRow
	for rows.Next() {
		var i GetBranchFromRootToRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ParentID,
			&i.Role,
			&i.Parts,
			&i.Content,
			&i.AgentName,
			&i.ToolName,
			&i.ToolCallID,
			&i.ToolArgs,
			&i.Model,
			&i.TokenCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessage = `-- name: GetMessage :one
SELECT id, session_id, parent_id, role, parts, content, agent_name, tool_name, tool_call_id, tool_args, model, token_count, created_at, updated_at, finished_at FROM messages WHERE id = ?
`

func (q *Queries) GetMessage(ctx context.Context, id string) (Message, error) {
	row := q.queryRow(ctx, q.getMessageStmt, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ParentID,
		&i.Role,
		&i.Parts,
		&i.Content,
		&i.AgentName,
		&i.ToolName,
		&i.ToolCallID,
		&i.ToolArgs,
		&i.Model,
		&i.TokenCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listMessagesBySession = `-- name: ListMessagesBySession :many
SELECT id, session_id, parent_id, role, parts, content, agent_name, tool_name, tool_call_id, tool_args, model, token_count, created_at, updated_at, finished_at FROM messages WHERE session_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error) {
	rows, err := q.query(ctx, q.listMessagesBySessionStmt, listMessagesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ParentID,
			&i.Role,
			&i.Parts,
			&i.Content,
			&i.AgentName,
			&i.ToolName,
			&i.ToolCallID,
			&i.ToolArgs,
			&i.Model,
			&i.TokenCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessage = `-- name: UpdateMessage :exec
UPDATE messages
SET content = COALESCE(?, content),
    parts = COALESCE(?, parts),
    finished_at = COALESCE(?, finished_at)
WHERE id = ?
`

type UpdateMessageParams struct {
	Content    sql.NullString `json:"content"`
	Parts      string         `json:"parts"`
	FinishedAt sql.NullInt64  `json:"finished_at"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) error {
	_, err := q.exec(ctx, q.updateMessageStmt, updateMessage,
		arg.Content,
		arg.Parts,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}
