// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Agent struct {
	Name         string         `json:"name"`
	SystemPrompt string         `json:"system_prompt"`
	Tools        string         `json:"tools"`
	Model        sql.NullString `json:"model"`
	ParentAgent  sql.NullString `json:"parent_agent"`
	Permissions  string         `json:"permissions"`
	ConfigPath   sql.NullString `json:"config_path"`
	LoadedAt     int64          `json:"loaded_at"`
}

type DelegationLog struct {
	ID              string         `json:"id"`
	ParentMessageID string         `json:"parent_message_id"`
	ChildAgentName  string         `json:"child_agent_name"`
	ChildSessionID  sql.NullString `json:"child_session_id"`
	TaskDescription string         `json:"task_description"`
	ResultSummary   sql.NullString `json:"result_summary"`
	DurationMs      sql.NullInt64  `json:"duration_ms"`
	CreatedAt       int64          `json:"created_at"`
}

type Memory struct {
	ID        string         `json:"id"`
	AgentName string         `json:"agent_name"`
	Key       string         `json:"key"`
	Value     string         `json:"value"`
	Category  sql.NullString `json:"category"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
}

type Message struct {
	ID         string         `json:"id"`
	SessionID  string         `json:"session_id"`
	ParentID   sql.NullString `json:"parent_id"`
	Role       string         `json:"role"`
	Parts      string         `json:"parts"`
	Content    sql.NullString `json:"content"`
	AgentName  sql.NullString `json:"agent_name"`
	ToolName   sql.NullString `json:"tool_name"`
	ToolCallID sql.NullString `json:"tool_call_id"`
	ToolArgs   sql.NullString `json:"tool_args"`
	Model      sql.NullString `json:"model"`
	TokenCount sql.NullInt64  `json:"token_count"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
	FinishedAt sql.NullInt64  `json:"finished_at"`
}

type Session struct {
	ID               string         `json:"id"`
	ParentSessionID  sql.NullString `json:"parent_session_id"`
	AgentName        string         `json:"agent_name"`
	Title            string         `json:"title"`
	ActiveLeafID     sql.NullString `json:"active_leaf_id"`
	Status           string         `json:"status"`
	MessageCount     int64          `json:"message_count"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	Cost             float64        `json:"cost"`
	UpdatedAt        int64          `json:"updated_at"`
	CreatedAt        int64          `json:"created_at"`
	SummaryMessageID sql.NullString `json:"summary_message_id"`
}
