// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error)
	CreateDelegationLog(ctx context.Context, arg CreateDelegationLogParams) (DelegationLog, error)
	CreateMemory(ctx context.Context, arg CreateMemoryParams) (Memory, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteAgent(ctx context.Context, name string) error
	DeleteMemory(ctx context.Context, id string) error
	DeleteMessage(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionMessages(ctx context.Context, sessionID string) error
	GetAgent(ctx context.Context, name string) (Agent, error)
	GetAllLeaves(ctx context.Context, arg GetAllLeavesParams) ([]Message, error)
	GetBranchFromRootTo(ctx context.Context, id string) ([]GetBranchFromRootToRow, error)
	GetMemory(ctx context.Context, arg GetMemoryParams) (Memory, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	ListAgents(ctx context.Context) ([]Agent, error)
	ListDelegationLogsBySession(ctx context.Context, sessionID string) ([]DelegationLog, error)
	ListMemoryByAgent(ctx context.Context, agentName string) ([]Memory, error)
	ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	ListSessions(ctx context.Context) ([]Session, error)
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
}

var _ Querier = (*Queries)(nil)
